In [2]:
import warnings
warnings.filterwarnings('ignore')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [3]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

pd.options.display.max_colwidth = 200
%matplotlib inline

In [4]:
df = pd.read_csv('./data/train_preprocess.csv')
df.head()

,sentence,fuel,machine,others,part,price,service
0,Saya memakai Honda Jazz GK5 tahun 2014 ( pertama meluncur ) . Mobil nya bagus dan enak sesuai moto nya menyenangkan untuk dikendarai,neutral,neutral,positive,neutral,neutral,neutral
1,Avanza kenapa jadi boros bensin begini dah ah. Baru diisi sudah mau setengah saja .,negative,neutral,neutral,neutral,neutral,neutral
2,"saran ku dan pengalaman ku , mending beli mobil niaga L300 atau canter . irit dan bandel .",positive,positive,neutral,neutral,neutral,neutral
3,Dari segi harga juga pajero lebih mahal 30 jutaan dibanding fortuner,neutral,neutral,neutral,neutral,positive,neutral
4,Kalo menurut gw enak pajero si,neutral,neutral,positive,neutral,neutral,neutral

In [5]:

stemmer = StemmerFactory().create_stemmer()
wpt = nltk.WordPunctTokenizer()
stopword_factory = StopWordRemoverFactory()

stopword = stopword_factory.get_stop_words()

def uncapitalize(doc):
    return doc.lower()


def normalize_document(doc):
    doc = uncapitalize(doc)
    doc = doc.strip()
    doc = wpt.tokenize(doc)
    doc = [stemmer.stem(word) for word in doc]
    doc = [word for word in doc if word not in stopword]
    doc = " ".join(doc)
    return doc

normalize_corpus = np.vectorize(normalize_document)

In [6]:
norm_corpus = normalize_corpus(list(df['sentence'])) 

# save to csv
df['clean_sentence'] = norm_corpus
df.to_csv('train_preprocess_stemmed.csv', index=False)
df.head()

,sentence,fuel,machine,others,part,price,service,clean_sentence
0,Saya memakai Honda Jazz GK5 tahun 2014 ( pertama meluncur ) . Mobil nya bagus dan enak sesuai moto nya menyenangkan untuk dikendarai,neutral,neutral,positive,neutral,neutral,neutral,pakai honda jazz gk5 tahun 2014 luncur mobil bagus sesuai moto senang kendara
1,Avanza kenapa jadi boros bensin begini dah ah. Baru diisi sudah mau setengah saja .,negative,neutral,neutral,neutral,neutral,neutral,avanza boros bensin dah ah isi tengah
2,"saran ku dan pengalaman ku , mending beli mobil niaga L300 atau canter . irit dan bandel .",positive,positive,neutral,neutral,neutral,neutral,saran ku alam ku mending beli mobil niaga l300 canter irit bandel
3,Dari segi harga juga pajero lebih mahal 30 jutaan dibanding fortuner,neutral,neutral,neutral,neutral,positive,neutral,segi harga pajero mahal 30 juta banding fortuner
4,Kalo menurut gw enak pajero si,neutral,neutral,positive,neutral,neutral,neutral,kalo gw pajero si

In [7]:
df['clean_sentence'] = norm_corpus

df.head()

,sentence,fuel,machine,others,part,price,service,clean_sentence
0,Saya memakai Honda Jazz GK5 tahun 2014 ( pertama meluncur ) . Mobil nya bagus dan enak sesuai moto nya menyenangkan untuk dikendarai,neutral,neutral,positive,neutral,neutral,neutral,pakai honda jazz gk5 tahun 2014 luncur mobil bagus sesuai moto senang kendara
1,Avanza kenapa jadi boros bensin begini dah ah. Baru diisi sudah mau setengah saja .,negative,neutral,neutral,neutral,neutral,neutral,avanza boros bensin dah ah isi tengah
2,"saran ku dan pengalaman ku , mending beli mobil niaga L300 atau canter . irit dan bandel .",positive,positive,neutral,neutral,neutral,neutral,saran ku alam ku mending beli mobil niaga l300 canter irit bandel
3,Dari segi harga juga pajero lebih mahal 30 jutaan dibanding fortuner,neutral,neutral,neutral,neutral,positive,neutral,segi harga pajero mahal 30 juta banding fortuner
4,Kalo menurut gw enak pajero si,neutral,neutral,positive,neutral,neutral,neutral,kalo gw pajero si

<h1>Bag Of Words Model</h1>

In [8]:
from sklearn.feature_extraction.text import CountVectorizer


cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(df['clean_sentence'])
cv_matrix

<810x1370 sparse matrix of type '<class 'numpy.int64'>'
	with 6226 stored elements in Compressed Sparse Row format>

In [9]:
print(cv_matrix)

  (0, 923)	1
  (0, 504)	1
  (0, 563)	1
  (0, 449)	1
  (0, 1202)	1
  (0, 44)	1
  (0, 745)	1
  (0, 815)	1
  (0, 163)	1
  (0, 1119)	1
  (0, 829)	1
  (0, 1106)	1
  (0, 639)	1
  (1, 148)	1
  (1, 237)	1
  (1, 204)	1
  (1, 315)	1
  (1, 88)	1
  (1, 538)	1
  (1, 1235)	1
  (2, 815)	1
  (2, 1075)	1
  (2, 681)	2
  (2, 99)	1
  (2, 789)	1
  :	:
  (806, 798)	1
  (806, 1179)	1
  (806, 477)	1
  (807, 163)	1
  (807, 417)	1
  (807, 87)	1
  (807, 617)	1
  (808, 537)	1
  (808, 483)	1
  (808, 830)	1
  (808, 1070)	1
  (808, 894)	1
  (808, 550)	1
  (808, 166)	1
  (808, 168)	1
  (808, 1320)	1
  (808, 780)	1
  (808, 690)	1
  (808, 441)	1
  (809, 483)	1
  (809, 374)	1
  (809, 263)	1
  (809, 377)	1
  (809, 229)	1
  (809, 1177)	1

In [10]:
cv_matrix = cv_matrix.toarray()
cv_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
vocab = cv.get_feature_names_out()
pd.DataFrame(cv_matrix, columns=vocab)

,000,0001,04,08,10,100,1000,11,118,12,...,yamaha,yamahaid,yamahaindonesia,yangg,yaudah,yg,ymh,yogyakarta,zaman,zr
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
807,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
809,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

<h1>Bag of N-Grams Model</h1>

In [12]:
bv = CountVectorizer(ngram_range=(2,2))
bv_matrix = bv.fit_transform(df['clean_sentence'])

bv_matrix = bv_matrix.toarray()
vocab = bv.get_feature_names_out()
pd.DataFrame(bv_matrix, columns=vocab)

,000 rupiah,000 sumpah,0001 ga,04 2008,08 family,10 juta,10 menit,10 tahun,10 udah,10 woi,...,yg kampung,yg keras,yg kes,yg kondang,yg menang,yg rush,yg seger,ymh awat,yogyakarta khawatir,zr harga
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
807,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
809,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

<h1>TF-IDF Model</h1>

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer

tt = TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True)
tt_matrix = tt.fit_transform(cv_matrix)

tt_matrix = tt_matrix.toarray()
vocab = cv.get_feature_names_out()
pd.DataFrame(np.round(tt_matrix, 2), columns=vocab)

,000,0001,04,08,10,100,1000,11,118,12,...,yamaha,yamahaid,yamahaindonesia,yangg,yaudah,yg,ymh,yogyakarta,zaman,zr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
809,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., norm='l2', use_idf=True, smooth_idf=True)
tv_matrix = tv.fit_transform(df['clean_sentence'])
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names_out()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

,000,0001,04,08,10,100,1000,11,118,12,...,yamaha,yamahaid,yamahaindonesia,yangg,yaudah,yg,ymh,yogyakarta,zaman,zr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
809,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<h1>Understanding the TF-IDF from Scratch</h1>

In [15]:
unique_words = list(
    set([word for doc in [doc.split() for doc in df['clean_sentence']] for word in doc])
)

# Create dictionary with unique words as keys, initialized to 0
def_feature_dict = {w: 0 for w in unique_words}
print(def_feature_dict)

{'nyaman': 0, 'buanyak': 0, 'mentok': 0, 'baju': 0, 'takut': 0, '2008': 0, 'dibandingin': 0, 'lebaran': 0, 'mimpi': 0, 'buang': 0, 'pilih': 0, 'nyedot': 0, 'cx3': 0, 'padan': 0, 'ergonomis': 0, 'impi': 0, 'spion': 0, 'umat': 0, 'tampung': 0, 'togosari': 0, '1000': 0, 'hahaha': 0, 'servis': 0, 'aman': 0, 'tubruk': 0, 'performa': 0, 'awet': 0, 'spirit': 0, 'mumpuni': 0, 'kenceng': 0, 'brio': 0, 'efek': 0, 'anugerah': 0, 'pulang': 0, 'baris': 0, 'pasar': 0, 'super': 0, 'besi': 0, 'seat': 0, 'montor': 0, 'saing': 0, 'ahas': 0, 'julang': 0, 'ehe': 0, '3': 0, 'gitu': 0, '537': 0, 'pinggir': 0, 'simpul': 0, 'urus': 0, 'ambil': 0, 'masuk2': 0, 'produk': 0, 'bagus': 0, 'nissan': 0, 'harga': 0, 'idam': 0, 'jalan': 0, 'jual': 0, 'segitu': 0, 'xpander': 0, 'dikit': 0, 'improvement': 0, 'tunggu': 0, '139': 0, '13': 0, '08': 0, 'ngaco': 0, 'layan': 0, 'ac': 0, 'nomor': 0, 'gue': 0, 'rumah': 0, 'type': 0, '90': 0, 'vario': 0, 'sinyal': 0, 'sungguh': 0, 'racing': 0, 'innova': 0, 'tangki': 0, 'online': 0, 'tepos': 0, 'nih': 0, 'cvt': 0, 'kesan': 0, 'lucu': 0, 'minggu': 0, 'gesit': 0, 'digunain': 0, 'bohong': 0, 'ane': 0, 'scumbag': 0, 'tipis': 0, 'ckd': 0, 'rezeki': 0, 'tunggang': 0, 'clearance': 0, 'nanya': 0, 'ngeliat': 0, 'cbu': 0, 'for': 0, 'abis': 0, 'coba': 0, 'l300': 0, 'duduk': 0, 'raja': 0, 'mahal': 0, 'kualitas': 0, 'jaga': 0, 'cenderung': 0, 'setia': 0, '14': 0, 'mahasiswa': 0, 'booster': 0, 'uang': 0, 'nm': 0, 'cewek': 0, 'laksana': 0, 'worth': 0, 'rembes': 0, 'semenjak': 0, 'suku': 0, 'ngerasa': 0, 'aneh': 0, 'kuliah': 0, 'prado': 0, 'profesi': 0, 'hadir': 0, 'juragan': 0, '2009': 0, 've': 0, 'looking': 0, 'shockbreaker': 0, 'presisi': 0, 'gabung': 0, 'penyok': 0, 'kandang': 0, 'lengkap': 0, 'hand': 0, 'gua': 0, 'curam': 0, 'adu': 0, 'jarang': 0, 'bintaro': 0, 'gelap': 0, 'lux': 0, 'livina': 0, 'gampang': 0, 'mikir': 0, '2013': 0, 'warna': 0, 'daihatsu': 0, 'formo': 0, 'karna': 0, 'margonda': 0, 'gl': 0, 'pondok': 0, 'cabe': 0, 'kosong': 0, 'parking': 0, 'siang': 0, 'nyuruh': 0, 'dicomot2': 0, 'beli': 0, 'vvti': 0, 'nahan': 0, 'pribadi': 0, 'ganjal': 0, 'bangga': 0, 'shifting': 0, '50': 0, 'atap': 0, 'suara': 0, 'rewel': 0, 'one': 0, 'mulu': 0, 'rusak': 0, 'nikmat': 0, 'kawasaki': 0, 'bosen': 0, 'pohon': 0, 'booking': 0, 'shift': 0, 'waras': 0, 'sempit': 0, 'velg': 0, 'sukses': 0, 'parkir': 0, 'bolak': 0, 'dinamis': 0, 'panggil': 0, 'mudik': 0, 'senyap': 0, 'bulat': 0, 'tugas': 0, 'sore': 0, 'malam': 0, 'aus': 0, 'inden': 0, 'abang': 0, 'ok': 0, 'trd': 0, 'tempuh': 0, 'angkut': 0, 'jawa': 0, 'sih': 0, 'test': 0, 'godzilla': 0, 'toyota': 0, '40': 0, 'pantes': 0, 'vtec': 0, 'kalang': 0, 'saranin': 0, 'intens': 0, 'motor': 0, 'saku': 0, 'lirik': 0, 'menggangu': 0, 'tes': 0, 'limbung': 0, 'stater': 0, 'hatta': 0, 'solar': 0, 'sukabumi': 0, 'mobilitas': 0, 'alam': 0, 'ku': 0, '4x4': 0, 'ground': 0, 'ganti': 0, 'tanding': 0, 'alus': 0, 'gerak': 0, 'jatinegara': 0, 'nerima': 0, 'gen': 0, 'impresif': 0, 'bobot': 0, '700': 0, 'good': 0, 'goblok': 0, 'sewa': 0, 'maksimal': 0, 'manuver': 0, 'seater': 0, 'kursi': 0, 'full': 0, 'mulus': 0, 'almaz': 0, 'bensin': 0, 'timur': 0, 'cuci': 0, 'pulau': 0, 'rendah': 0, 'bang': 0, 'situ': 0, 'datsun': 0, 'muat': 0, 'black': 0, 'unik': 0, 'li': 0, 'security': 0, 'asa': 0, 'jaya': 0, 'suzuki': 0, 'tanjak': 0, 'untung': 0, 'normal': 0, 'axic': 0, 'merek': 0, 'kalkulasi': 0, 'turun': 0, 'vultus': 0, 'keliling': 0, 'pantat': 0, 'injektor': 0, 'mesin': 0, 'berat': 0, 'sepeda': 0, 'lambat': 0, 'merangsek': 0, 'stylish': 0, 'barang': 0, 'logo': 0, 'helm': 0, 'nabrak': 0, '612': 0, 'vrz': 0, 'premium': 0, 'kagak': 0, 'exceed': 0, 'bodi': 0, 'serasa': 0, 'drive': 0, 'lot': 0, 'taruna': 0, 'body': 0, 'yg': 0, 'pt': 0, 'avanza': 0, 'dijadiin': 0, 'sunroof': 0, 'brake': 0, 'mazda': 0, 'letoy': 0, 'nama': 0, 'sumpah': 0, 'standard': 0, '60': 0, 'anak': 0, 'bakar': 0, 'lebar': 0, 'nanggung': 0, 'kota': 0, 'jujur': 0, 'park': 0, 'cortez': 0, 'cooper': 0, 'wanita': 0, 'jiwa': 0, 'brv': 0, 'layang': 0, 'ring': 0, 'ama': 0, 'pegal': 0, '000': 0, 'otolovers': 0, 'gk5': 0, 'sebener': 0, 'autoland': 0, 'fitur': 0, 'karakter': 0, 'inova': 0, 'dikerjain': 0, 'ah': 0, 'nunggu': 0, 'prefer': 0, 'kes': 0, '160': 0, 'car': 0, 'telepon': 0, 'bebas': 0, 'polisi': 0, 'keseluruha': 0, 'bosan': 0, 'monoton': 0, '16': 0, 'cat': 0, 'elegan': 0, 'legain': 0, 'ganggu': 0, 'daring': 0, 'part': 0, 'fasilitas': 0, 'customer': 0, 'pintar': 0, 'finishing': 0, 'alias': 0, 'operasional': 0, 'suspensi': 0, 'kelas': 0, 'filter': 0, 'modal': 0, 'kabin': 0, 'ajar': 0, 'touring': 0, 'perempuan': 0, 'optimal': 0, 'ramah': 0, 'jeroan': 0, 'yangg': 0, 'kopling': 0, 'injak': 0, 'auto': 0, 'ramadhan': 0, 'veloz': 0, 'ngga': 0, 'mending': 0, 'proyek': 0, 'so': 0, 'tubeless': 0, 'top': 0, 'anugrah': 0, 'ahass': 0, 'nambah': 0, 'paket': 0, 'door': 0, 'tegak': 0, 'drpd': 0, 'bmw': 0, 'jenis': 0, 'tangguh': 0, 'tebal': 0, 'sembunyi': 0, 'bangku': 0, 'picik': 0, 'ubah': 0, 'zaman': 0, '86': 0, 'tani': 0, 'hp': 0, 'alya': 0, 'shock': 0, 'banget': 0, '-': 0, 'canter': 0, 'kijang': 0, 'gps': 0, 'sentuh': 0, 'handling': 0, 'eye': 0, 'buy': 0, 'irit': 0, 'praktis': 0, 'pajero': 0, 'and': 0, '2': 0, 'dlx': 0, 'menit': 0, 'unibody': 0, 'jarak': 0, 'yamahaid': 0, 'berisik': 0, 'cina': 0, 'seven': 0, 'hemat': 0, 'wulling': 0, 'sadar': 0, 'hadeh': 0, 'penuh': 0, '167': 0, 'kilas': 0, 'cs': 0, 'aerox': 0, 'onderdil': 0, 'selera': 0, 'lengang': 0, 'gila': 0, 'ramai': 0, 'sparepart': 0, 'ngalahin': 0, 'masya': 0, 'sprint': 0, 'jamin': 0, '4': 0, 'pelihara': 0, 'negeri': 0, 'orientasi': 0, 'milik': 0, 'pagi': 0, '1': 0, 'kelapa': 0, 'sporty': 0, 'ekonomis': 0, 'lancar': 0, 'sisingamangaraja': 0, 'kaleng': 0, 'bingung': 0, 'tetep': 0, 'hehe': 0, 'wheel': 0, 'sakit': 0, 'pluit': 0, 'lbh': 0, 'isi': 0, 'habis': 0, 'vario125': 0, 'sopir': 0, 'dealer': 0, 'ngapain': 0, 'it': 0, 'jatuh': 0, 'international': 0, 'via': 0, 'suka': 0, 'cikampek': 0, 'pajak': 0, 'astrido': 0, 'menesal': 0, 'rata': 0, '1200': 0, 'freed': 0, 'varian': 0, 'telak': 0, 'lampu': 0, 'bongkar': 0, 'biosolar': 0, '04': 0, 'awang': 0, 'kalo': 0, 'lincah': 0, 'hmm': 0, 'tinggal': 0, 'badan': 0, 'kadang': 0, 'keren': 0, 'wuling': 0, 'usia': 0, 'beban': 0, '180': 0, 'power': 0, 'buruk': 0, 'prima': 0, 'alhamdulillah': 0, 'masyarakat': 0, 'sma': 0, '1800': 0, 'nasional': 0, 'loh': 0, 'beneran': 0, 'juara': 0, 'dijanjiin': 0, 'susah': 0, 'becus': 0, 'muda': 0, '125': 0, 'crv': 0, 'modern': 0, 'cx': 0, 'grab': 0, 'cantik': 0, 'bener': 0, 'tarik': 0, 'bahan': 0, 'manis': 0, 'penyot': 0, 'xi': 0, 'soak': 0, 'fokus': 0, 'overall': 0, 'jangkau': 0, 'murah': 0, 'jepang': 0, 'oli': 0, 'beda': 0, 'bu': 0, 'vespa': 0, 'spoiler': 0, 'great': 0, 'kepincut': 0, 'pamulang': 0, 'gengsi': 0, 'street': 0, 'aki': 0, 'toyotaid': 0, 'ruang': 0, 'kembang': 0, 'juni': 0, 'referensi': 0, 'langgan': 0, 'sampe': 0, 'mah': 0, 'proporsional': 0, 'map': 0, 'santai': 0, 'cepat': 0, 'soekarno': 0, '183': 0, 'jam': 0, 'saudara': 0, 'umur': 0, 'selamat': 0, 'kendala': 0, 'steering': 0, '2017': 0, 'njrit': 0, 'sahabat': 0, 'ne': 0, 'maksa': 0, 'ekstrem': 0, 'banci': 0, 'agustus': 0, 'efisiensi': 0, 'dasboard': 0, 'moto': 0, 'mainin': 0, 'gembira': 0, 'umum': 0, 'kendara': 0, 'numpang': 0, 'rival': 0, 'thanks': 0, '140': 0, 'sampah': 0, 'cipularang': 0, 'rush': 0, 'capai': 0, 'facelift': 0, 'staf': 0, 'kayak': 0, '40thyamaha': 0, 'bosenin': 0, 'hasil': 0, 'recommended': 0, 'ketimbang': 0, 'tp': 0, 'rombong': 0, 'volume': 0, 'senang': 0, 'rutin': 0, 'troli': 0, 'lebay': 0, 'dewasa': 0, 'saran': 0, 'non': 0, 'max': 0, '1308': 0, 'mitshubisi': 0, 'service': 0, '28': 0, 'ampun': 0, 'kebut': 0, 'ch': 0, 'kretek': 0, 'alhamdullilah': 0, 'cabang': 0, 'kabel': 0, 'hold': 0, 'konsumsi': 0, 'teknologi': 0, 'tari': 0, 'problem': 0, 'tol': 0, 'moga': 0, 'tasikmalaya': 0, 'hitam': 0, 'budget': 0, 'safety': 0, 'biar': 0, 'worldwide': 0, 'jaring': 0, 'handal': 0, 'kapok': 0, 'gw': 0, 'driver': 0, '120': 0, 'akselerasi': 0, 'confero': 0, 'ignis': 0, 'emang': 0, '2006': 0, 'waktu': 0, 'fitra': 0, 'cakep': 0, 'rekomendasi': 0, '2018': 0, 'minimal': 0, 'huh': 0, 'kampus': 0, 'over': 0, 'faktor': 0, 'mas': 0, 'dual': 0, 'cinta': 0, 'kaku': 0, 'baca': 0, 'harap': 0, 'gimana': 0, 'rasio': 0, 'perspektif': 0, '20': 0, '12': 0, 'biaya': 0, 'ni': 0, 'mampir': 0, 'komplain': 0, 'rpm': 0, 'ngelitik': 0, 'desain': 0, 'tukar': 0, 'bikin': 0, 'posisi': 0, 'girl': 0, 'bandel': 0, 'framless': 0, 'exterior': 0, 'main': 0, 'unta': 0, 'olah': 0, 'nopol': 0, 'lemah': 0, 'spesifikasi': 0, 'bebek': 0, 'aerodinamis': 0, 'selesai': 0, 'torsi': 0, 'tenang': 0, 'ala': 0, 'versi': 0, 'hondaarista': 0, 'transmisi': 0, 'sulit': 0, 'spert': 0, 'cup': 0, 'susun': 0, 'pas': 0, 'new': 0, 'kampung': 0, 'pengaruh': 0, 'bandung': 0, 'athlete': 0, 'efisien': 0, 'panther': 0, 'bgt': 0, 'minor': 0, 'abal2': 0, 'sepi': 0, 'simpan': 0, 'catching': 0, 'standar': 0, 'kotor': 0, 'haha': 0, 'butuh': 0, '2005': 0, 'eksterior': 0, 'jok': 0, 'blong': 0, 'boros': 0, 'gahar': 0, 'tunas': 0, 'inline': 0, 'agam': 0, 'master': 0, 'screen': 0, 'ulang': 0, 'pria': 0, 'technology': 0, 'off': 0, 'series': 0, 'sesuai': 0, 'zr': 0, '30': 0, '70': 0, 'muka': 0, 'gantung': 0, '7': 0, 'kekar': 0, 'kempes': 0, 'batre': 0, 'papa': 0, 'mogok': 0, 'balap': 0, 'mobil': 0, '1500': 0, 'aja': 0, 'utama': 0, 'agresif': 0, '2004': 0, 'dp': 0, 'tolong': 0, 'laju': 0, 'provinsi': 0, 'ngambil': 0, 'milih': 0, 'like': 0, '2011': 0, 'low': 0, 'greget': 0, 'sport': 0, 'cylinder': 0, '135': 0, 'tipe': 0, 'berkat': 0, 'cuman': 0, 'calya': 0, 'ringkih': 0, 'kaca': 0, 'megang': 0, 'terang': 0, 'xv': 0, 'ngaret': 0, 'change': 0, 'fortuner': 0, 'keburu': 0, 'hondajazz': 0, 'ngejeduk': 0, 'asoy': 0, 'cm': 0, 'sepele': 0, 'pokok': 0, '0001': 0, 'sigra': 0, '2001': 0, 'klo': 0, 'impresi': 0, 'bados05': 0, 'woi': 0, 'percaya': 0, 'konter': 0, 'ekonomi': 0, '25': 0, 'helpful': 0, 'asuransi': 0, 'bbm': 0, 'prestige': 0, 'terlau': 0, 'tuh': 0, 'nyala': 0, 'kuat': 0, 'rambut': 0, 'iip': 0, 'kecuali': 0, 'sasis': 0, 'konsumen': 0, 'dah': 0, 'unit': 0, 'alas': 0, 'double': 0, 'rem': 0, 'tau': 0, 'plafon': 0, 'pandang': 0, 'scoopy': 0, 'to': 0, 'dobel': 0, 'family': 0, 'cadang': 0, 'dicsitu': 0, 'dll': 0, 'gading': 0, 'dompet': 0, 'kalem': 0, 'daya': 0, 'isuzu': 0, 'khas': 0, 'santa': 0, 'lupa': 0, 'jakarta': 0, 'mu': 0, 'mati': 0, 'gigi': 0, 'combi': 0, 'taksi': 0, 'riah': 0, 'seksi': 0, 'cc': 0, 'bilang': 0, 'dipake': 0, 'klasik': 0, 'ymh': 0, 'review': 0, 'coi': 0, 'ayla': 0, 'giat': 0, 'powerful': 0, 'minum': 0, 'sales': 0, 'lamp': 0, 'mekanik': 0, 'sudut': 0, 'pegang': 0, 'kondisi': 0, 'tidur': 0, 'alokasi': 0, 'sirion': 0, 'jelek': 0, 'banyakin': 0, 'bukti': 0, 'sanggup': 0, '2016': 0, 'avsen': 0, 'yamahaindonesia': 0, 'kejar': 0, '2014': 0, 'yogyakarta': 0, 'antre': 0, 'mungil': 0, 'gang': 0, 'kemudi': 0, 'dahsyat': 0, 'lempeng': 0, 'slalu': 0, 'ga': 0, 'lekuk': 0, '150': 0, '2020': 0, 'satya': 0, 'buah': 0, 'vva': 0, 'injeksi': 0, 'single': 0, 'tampang': 0, 'telescopic': 0, 'hr': 0, 'bunyi': 0, 'supra': 0, 'gt': 0, '2015': 0, 'turbo': 0, 'air': 0, '118': 0, 'minat': 0, 'nyesel': 0, 'belah': 0, 'avg': 0, 'tonjol': 0, '155': 0, 'wuiling': 0, 'pake': 0, 'parah': 0, 'karir': 0, '10': 0, 'teman': 0, 'negara': 0, 'pabrikan': 0, 'meadai': 0, 'sisi': 0, 'model': 0, 'lexi': 0, 'gas': 0, 'hrv': 0, 'dapet': 0, 'kapsul': 0, 'window': 0, 'kagum': 0, '500': 0, 'terios': 0, 'duit': 0, 'at': 0, 'mantab': 0, 'uras': 0, 'udh': 0, 'avs': 0, 'lo': 0, 'roll': 0, 'legenda': 0, 'rupiah': 0, 'ribet': 0, 'bocor': 0, 'elektronik': 0, 'kambing': 0, 'kasta': 0, 'radiator': 0, 'kopi': 0, 'ledak': 0, 'stabil': 0, 'arah': 0, 'nagrek': 0, 'salah': 0, 'komplit': 0, 'plus': 0, 'allah': 0, 'gak': 0, 'wow': 0, 'ain': 0, '15': 0, 'luas': 0, 'gardan': 0, 'ayah': 0, 'sekolah': 0, 'gk': 0, 'after': 0, 'kualifikasi': 0, '6': 0, 'andal': 0, 'surabaya': 0, 'simpel': 0, 'khawatir': 0, 'aspek': 0, 'ganteng': 0, 'jantan': 0, 'alloy': 0, 'major': 0, 'ceper': 0, 'jadul': 0, 'honda': 0, 'scooy': 0, 'gan': 0, 'dieng': 0, 'maaf': 0, 'salip': 0, 'toko': 0, 'teknisi': 0, 'holders': 0, 'mt': 0, 'pol': 0, 'suv': 0, 'lumayan': 0, 'niaga': 0, 'baleno': 0, 'awat': 0, 'instagram': 0, 'spacy': 0, 'serius': 0, 'terlihar': 0, 'benah': 0, 'bentuk': 0, 'ban': 0, 'konde': 0, 'maluin': 0, 'radio': 0, 'wagon': 0, 'tumpang': 0, 'nggak': 0, 'deteksi': 0, 'beat': 0, 'engine': 0, 'cocok': 0, 'speed': 0, 'kompetitif': 0, 'mirror': 0, 'liat': 0, 'generasi': 0, 'duh': 0, 'mio': 0, 'canggih': 0, 'nmax': 0, 'mitsubishi': 0, 'bagasi': 0, '2000': 0, 'kph': 0, 'mobilio': 0, 'high': 0, 'banting': 0, 'lega': 0, 'halogen': 0, 'plastik': 0, 'libur': 0, 'rental': 0, 'rute': 0, 'manual': 0, 'tachometer': 0, 'cidodol': 0, 'dukung': 0, 'kaya': 0, 'holder': 0, 'in': 0, 'yamaha': 0, 'jati': 0, 'mantap': 0, 'gaspol': 0, 'head': 0, 'rs': 0, 'deket': 0, 'pelan': 0, 'bal': 0, 'sesal': 0, 'kmh': 0, 'doang': 0, 'chr': 0, 'semi': 0, 'aspal': 0, 'xenia': 0, 'hajar': 0, 'deh': 0, 'id': 0, 'sonic': 0, 'colok': 0, 'tetangga': 0, 'vvt': 0, 'sistem': 0, 'musim': 0, 'lcgc': 0, '300': 0, 'tualang': 0, 'kantong': 0, 'limiter': 0, 'diesel': 0, 'hobi': 0, 'tinggi': 0, 'monitor': 0, 'tawar': 0, '0': 0, 'bawa': 0, 'bengkel': 0, 'not': 0, 'seger': 0, 'sensor': 0, 'udah': 0, 'esemka': 0, 'knock': 0, '400': 0, 'tajam': 0, 'gari': 0, 'pedal': 0, 'accu': 0, 'ditinggalin': 0, 'aeorodinamis': 0, '2003': 0, 'tiada': 0, 'led': 0, 'cabin': 0, 'perang': 0, 'operator': 0, 'hati': 0, 'unggul': 0, 'pesan': 0, 'gunung': 0, '80': 0, 'enteng': 0, 'ken': 0, 'payah': 0, 'noted': 0, 'bayi': 0, 'lingkung': 0, 'mental': 0, 'ultra': 0, 'silinder': 0, 'kejam': 0, 'keras': 0, 'daihatsuind': 0, 'empuk': 0, 'kasar': 0, 'lintas': 0, 'otr': 0, 'halus': 0, 'kondang': 0, 'cross': 0, 'gx': 0, 'kalah': 0, '5': 0, 'cengeng': 0, '9': 0, 'gede': 0, 'modifikasi': 0, 'tipissss': 0, 'gaya': 0, 'terima': 0, 'tua': 0, 'dasbor': 0, 'kemarin': 0, '2019': 0, 'puluh': 0, 'putar': 0, 'hard': 0, 'pelit': 0, 'style': 0, 'poin': 0, 'tur': 0, 'lawak': 0, 'ringan': 0, 'autobest': 0, 'matraman': 0, 'time': 0, 'mpv': 0, 'malas': 0, 'astra': 0, 'tahun': 0, 'capek': 0, 'mewah': 0, '1300': 0, 'kehandalan': 0, 'kilometer': 0, 'brand': 0, 'all': 0, 'jayakarta': 0, 'bos': 0, 'bekas': 0, 'sangka': 0, 'auto2000id': 0, 'ribu': 0, 'edukasi': 0, 'kasih': 0, '100': 0, 'juli': 0, 'road': 0, 'keliru': 0, 'kere': 0, 'keluh': 0, 'macet': 0, 'pakem': 0, 'smartkey': 0, 'muas': 0, 'ngebenerin': 0, 'oke': 0, 'gado2': 0, 'semrawut': 0, 'antri': 0, 'dakar': 0, 'iya': 0, 'kendali': 0, 'wikwikwik': 0, 'heart': 0, 'ertiga': 0, 'purnajual': 0, 'joss': 0, 'insyaallah': 0, 'jalur': 0, 'tingkat': 0, 'xeli': 0, 'bom': 0, 'esp': 0, 'bag': 0, 'poso': 0, 'tenaga': 0, '11': 0, 'bayar': 0, 'kulit': 0, 'medan': 0, 'pergi': 0, 'indonesia': 0, 'bahagia': 0, 'sel': 0, 'sama2': 0, 'pcx': 0, 'istimewa': 0, 'matic': 0, 'mantep': 0, 'gratis': 0, 'juluk': 0, 'kondangan': 0, 'deluxe': 0, 'lmpv': 0, 'status': 0, 'dingin': 0, 'baret': 0, 'alat': 0, 'semir': 0, 'wajar': 0, 'design': 0, 'biji': 0, 'giias': 0, 'kepala': 0, 'luwes': 0, 'variasi': 0, 'kapasitas': 0, 'rear': 0, '2jt': 0, '2007': 0, 'locking': 0, 'starter': 0, 'dunia': 0, 'klaim': 0, 'tolak': 0, 'nan': 0, 'betah': 0, 'juta': 0, 'rigid': 0, 'bro': 0, 'keluarga': 0, 'maknyus': 0, 'paddle': 0, 'tikung': 0, 'lawan2': 0, 'berlian': 0, 'ketok': 0, 'tara': 0, 'indah': 0, 'faedah': 0, 'ragu': 0, 'jasa': 0, 'liter': 0, 'sabar': 0, 'maju': 0, 'tukang': 0, 'gender': 0, 'city': 0, 'ih': 0, 'karimun': 0, 'usaha': 0, 'aduh': 0, 'paksa': 0, '8': 0, 'sil': 0, 'interior': 0, 'hujan': 0, 'langit': 0, 'ngotot': 0, 'money': 0, 'beres': 0, 'frame': 0, 'gagah': 0, 'henti': 0, 'luncur': 0, 'adik': 0, 'price': 0, 'tas': 0, 'hebat': 0, 'toolkits': 0, 'bagusin': 0, 'layak': 0, 'km': 0, 'xexi': 0, 'tengah': 0, 'tahan': 0, '145': 0, 'suruh': 0, 'rame': 0, 'guncang': 0, 'banding': 0, 'asli': 0, 'overpriced': 0, 'upgrade': 0, 'pakai': 0, 'standart': 0, 'gtr': 0, 'delapan': 0, 'sub': 0, 'biru': 0, 'sebar': 0, 'rawan': 0, 'nilai': 0, 'film': 0, 'incar': 0, 'samping': 0, 'cari': 0, 'goyang': 0, 'kecewa': 0, 'sumatra': 0, 'cr': 0, 'mudah': 0, 'ning': 0, 'yaudah': 0, 'jangkung': 0, 'ajak': 0, 'puyeng': 0, 'grand': 0, 'anjing': 0, 'temu': 0, 'linaradj': 0, 'fi': 0, 'roda': 0, 'sayang': 0, 'an': 0, 'kaki': 0, 'kencang': 0, 'down': 0, 'ukur': 0, '3sz': 0, 'heran': 0, 'abs': 0, 'jazz': 0, 'pintu': 0, 'jgn': 0, 'mentul': 0, 'alami': 0, 'value': 0, 'tampil': 0, 'leluasa': 0, 'puas': 0, 'menang': 0, 'kak': 0, 'lari': 0, 'kompetitor': 0, 'simple': 0, 'center': 0, 'segi': 0, 'yah': 0, '2010': 0, 'crossover': 0, 'recall': 0, 'kedap': 0, 'kontroler': 0, 'nebeng': 0, 'kece': 0, 'resmi': 0, 'rapi': 0, 'kokoh': 0, 'sempurna': 0, 'nampak': 0, 'malu': 0, 'panas': 0, 'erti': 0, 'yahama': 0, 'monokok': 0, 'gemas': 0, 'agya': 0, 'spbu': 0, 'altis': 0, 'minim': 0, 'si': 0, 'wicaksana': 0, 'hidup': 0, 'angin': 0, 'diam': 0, 'om': 0, 'fun': 0, 'tim': 0, 'bonceng': 0, 'setir': 0, 'trus': 0, 'pelosok': 0, 'undi': 0, 'rentan': 0, 'terjal': 0, 'on': 0, 'pusing': 0, 'r35': 0, 'mini': 0}

In [16]:
from collections import Counter

bow_features = []

for doc in df['clean_sentence']:
    bow_feature = Counter(doc.split())
    all_features = Counter(def_feature_dict)
    bow_feature.update(all_features)
    bow_features.append(bow_feature)
    
bow_features = pd.DataFrame(bow_features)
bow_features

,pakai,honda,jazz,gk5,tahun,2014,luncur,mobil,bagus,sesuai,...,setir,trus,pelosok,undi,rentan,terjal,on,pusing,r35,mini
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
806,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
807,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
809,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
import scipy.sparse as sp
feature_names = list(bow_features.columns)

df_bow = np.diff(sp.csc_matrix(bow_features, dtype=int).indptr)
df_bow = 1 + df_bow

# show smoothened version of document frequencies
pd.DataFrame([df_bow], columns=feature_names)

,pakai,honda,jazz,gk5,tahun,2014,luncur,mobil,bagus,sesuai,...,setir,trus,pelosok,undi,rentan,terjal,on,pusing,r35,mini
0,94,93,15,2,48,4,2,157,61,4,...,6,2,2,2,2,3,2,2,2,4

In [18]:
#compute inverse document frequency
total_docs = 1 + len(df['clean_sentence'])
print(total_docs)

total_docs_float = float(total_docs)

idf = 1.0 + np.log(float(total_docs_float)/ df_bow)

print(idf)
# show smoothened version of idf
pd.DataFrame([np.round(idf, 2)], columns=feature_names)

811
[3.15497327 3.16566856 4.99021785 ... 7.00512087 7.00512087 6.31197369]

,pakai,honda,jazz,gk5,tahun,2014,luncur,mobil,bagus,sesuai,...,setir,trus,pelosok,undi,rentan,terjal,on,pusing,r35,mini
0,3.15,3.17,4.99,7.01,3.83,6.31,7.01,2.64,3.59,6.31,...,5.91,7.01,7.01,7.01,7.01,6.6,7.01,7.01,7.01,6.31

In [19]:
# compute idf diagonal matrix
total_features = bow_features.shape[1]
idf_diag = sp.spdiags(idf, diags=0, m=total_features, n=total_features)
idf_dense = idf_diag.todense()

#print the idf diagonal matrix
pd.DataFrame(np.round(idf_dense, 2))

,0,1,2,3,4,5,6,7,8,9,...,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380
0,3.15,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
1,0.00,3.17,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
2,0.00,0.00,4.99,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
3,0.00,0.00,0.00,7.01,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
4,0.00,0.00,0.00,0.00,3.83,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.6,0.00,0.00,0.00,0.00
1377,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.01,0.00,0.00,0.00
1378,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,7.01,0.00,0.00
1379,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,7.01,0.00
1380,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,6.31

In [20]:
# compute tfidf feature matrix
tf = np.array(bow_features, dtype='float64')
tfidf = tf * idf
#view raw tfidf feature matrix
pd.DataFrame(np.round(tfidf, 2), columns=feature_names)

,pakai,honda,jazz,gk5,tahun,2014,luncur,mobil,bagus,sesuai,...,setir,trus,pelosok,undi,rentan,terjal,on,pusing,r35,mini
0,3.15,3.17,4.99,7.01,3.83,6.31,7.01,2.64,3.59,6.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.64,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
806,3.15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.59,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
808,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
809,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
from numpy.linalg import norm
# compute L2 norms
norms = norm(tfidf, axis=1)

#print norms for each document
print (np.round(norms, 3))

[18.8   14.079 19.836 13.245  9.98  16.373 12.256 10.142 16.277 18.094
 18.458 16.348 13.276 16.584 25.119  9.558 18.088 21.364 16.47  10.63
 14.72  18.525 16.678 12.084 15.854 13.786  6.066 11.176  8.179 17.021
  9.418 18.007 10.977 13.728  8.317 10.675 17.511 21.757 13.895 10.941
 17.244  9.618 15.913  8.614 15.443 16.487 15.417 11.987 17.77  10.168
 13.496 20.206 24.469 20.606 15.821 17.225 19.13  16.016 15.554  6.656
 15.515 20.984 19.222 14.917 19.517 24.446 16.428 15.758 11.626 22.389
 15.479  9.509 10.219  8.991 15.643 16.915 18.896 21.8   17.147 20.428
 11.277 21.579 16.682 14.987  9.636 20.244 11.836 11.662  6.902 19.718
 16.82  12.15  21.532  8.794 18.268 17.919  9.408 10.822 16.667 13.791
 27.458  9.81  20.429 22.737 14.944 19.002 12.781 11.798 15.713 20.057
  8.103 13.151 23.388 14.708 19.941 19.789 11.118 15.447 10.366  7.38
 13.984 11.325 10.338 10.756 10.71  29.711 13.478  6.133 12.599 18.078
 20.918 10.439  7.398  8.869  9.086 14.35  14.399 10.074 13.823 11.937
 19.451 14.06  11.538  7.149  9.789 17.202  9.544 11.144 10.697 20.75
 17.606 11.765  9.231 16.241 13.162  8.524 25.088 14.358 10.652 10.26
 17.128 13.881 16.584 19.379 36.487 18.878 19.573 14.277 10.41  13.277
  9.789 26.419 17.071 14.54  19.348  9.451 14.55  19.028 18.278 11.868
 13.386 21.232  8.202 21.411 12.195  8.855 15.691 20.718 13.095 13.567
 14.799  7.531 12.73  20.049 11.15  11.409 15.401 14.832 15.256 18.2
 12.974 13.666 18.992 26.948 17.699  9.293 13.411 22.67   8.408  9.104
 12.309  9.492 13.445 16.821 12.565 12.719 13.34  16.487 15.491 17.305
 17.446 21.839 12.046  9.115 10.574 20.997 13.666  9.018 19.891 10.241
 18.897 16.43  14.721 14.926 18.101 13.413 18.486  9.747 14.049 16.401
  9.802 11.112 10.396 15.267 18.774 13.905  8.88  20.372 23.996 22.82
 12.767 21.141 17.519 24.707 19.629 18.305 15.427 16.995 16.558 14.74
  8.976 11.254 14.563  9.122 14.329 16.779 18.693 16.837  9.49  18.541
 17.228 10.354 25.301 18.1   19.477 13.62   8.538 15.477  9.312 18.604
 20.148 21.902 18.837 13.015 11.533 14.948  9.778 18.899 27.304 23.08
 15.721 14.641 18.116 14.007 17.01  14.376 20.181 18.047 19.671 13.588
 11.847 22.021 14.77  17.117  9.328 19.289 18.4   10.09   6.793 17.964
 14.365  8.477 27.8   19.197 12.798 13.014 20.207  7.398 17.015 21.715
 10.034 16.804  9.611 16.439 19.913 19.532 25.054 17.375 10.26  13.884
 12.662  8.68  24.784 14.487 22.734 14.136 14.566 20.596  9.693 11.884
 15.507 12.832 13.815 12.735 13.428 15.002 19.641 10.231  7.235 11.788
 15.099 12.265  9.138 10.227 18.766 17.19  27.811 14.646 10.973 15.278
  7.007  9.099 21.859 23.622 16.613 10.805 19.155 10.842 18.459 18.651
 11.692 12.741 11.107 11.741 28.753 13.812 11.039  7.769 17.465  9.403
 17.86  22.754 11.326 12.77  19.716 14.843 14.984 12.899 13.338 14.166
 13.459  7.392 12.178 13.744 18.349 11.756 14.    17.555 17.136 16.363
 13.631 19.279 14.129  8.739 16.35  13.889 17.136 10.784 26.658 16.8
 15.784 11.734 15.242 16.53  12.577 14.95  22.784 18.289 17.62  10.201
 17.663 12.444 11.441 15.72  15.51  11.571 15.239 17.282 14.516 19.482
 20.263 13.188 14.859 16.36   9.829 14.941 10.659  9.98  11.245  8.732
 13.973 13.466 11.178 13.315 14.092 16.907 11.432  9.989 14.365 15.956
 14.805 10.434 10.508 24.383 11.846 16.805 20.108 24.167 12.172 30.817
 12.22   6.59  13.978 11.819 23.407 11.902 11.801 10.353 15.631 10.899
 19.437 14.256 16.474 21.414 19.875  9.342  7.148 19.889 12.573 14.087
 14.632 15.662 24.956 10.844 21.722 13.131 22.276 16.927 19.481 11.333
 11.645 17.398 16.13  14.781  6.388 14.966 14.922 16.883 10.3   17.439
 13.718 10.195 17.143  8.539 18.922 16.464 13.198 13.733 15.967 11.692
 16.024 14.759 13.977 12.845 18.315 15.354 12.713  9.025 11.335 18.128
 11.92  15.195 14.31  16.474 15.094  9.286 14.44  12.787 13.625 21.427
 15.79  17.228 12.36  15.584 15.559 23.467 12.677 13.251 16.973 13.924
  8.764  7.813 11.493 14.368  7.356 16.042 12.361 14.185 20.73   9.029
 11.648 12.834 13.19  11.646 13.212 11.25  12.523 31.441 12.551 19.108
 10.804 16.162 20.493 16.679 13.427 14.069 13.003 17.165 10.826 15.318
 18.015 13.771 10.101 16.721 28.865  9.208 12.824 11.256 10.995 15.611
  8.152  8.512 10.823 10.395  9.624 15.093 13.572 12.026 10.947 15.024
 16.062  9.781  9.599 17.353 10.571 12.141 15.227 20.952 16.922  9.849
  9.768 20.363 15.457 14.548  9.45  15.496 23.052 13.78  17.965 10.736
 13.269 18.911 13.911 12.838 12.921  8.502 14.123 14.108 17.606 11.301
 10.881 19.35  10.775  7.17   8.962 20.783 10.707 12.595 21.126 12.181
  9.187 12.994 14.621 13.883 10.158 14.827 17.043 21.649 15.485 25.056
 15.52  14.082  9.474 14.154 14.242 11.667 17.438 20.618 10.379  6.801
 13.894 17.618 18.316 20.269 10.5   24.207 11.885 14.271 24.742 11.413
  8.441 13.922 12.161 13.721 13.648  8.124 17.145 21.905 10.776  6.638
 12.236 16.822  8.272 11.728 18.6   13.562 18.729 17.84  11.256  9.367
  8.877 15.207 17.971 15.846 13.485 23.275  9.615  9.197 13.38  15.809
 21.085 13.25  19.136 15.192 18.049 10.22  12.926 11.506 24.569 14.744
 16.929 15.992 21.927  9.045  9.236 10.299 18.687 17.397 15.208 16.551
 16.738 15.765 23.492  6.652 11.277 13.169 20.    24.421 14.156  7.507
 15.307 14.096 13.739 17.339 11.431 13.464 14.652 18.326 20.069  7.605
 13.312 13.707  9.797 17.747 10.328 18.253 12.411 13.396 11.924 17.083
 14.46   9.046 18.805 21.231  9.095 16.286 10.246  9.613 14.356 18.057
 17.547 14.95  19.71   6.461  8.974 12.54  15.054 14.376 11.863 11.476
 11.806 15.491  8.621 17.601 20.399  6.637 21.521 10.263 15.949 12.224
 24.78   9.774  8.29  10.385 16.272 14.228 12.107 12.611 16.469 18.781
 13.411 16.915 13.23  12.096 15.109 15.616 10.537 12.293 12.65  11.382
  8.935 26.062  8.129 10.435 20.305 10.181 16.64  20.923  9.802 21.794
 13.355 23.165 13.107 16.37  10.987 12.719 12.596  9.597 17.475 12.614]

In [22]:
norm_tfidf = tfidf / norms[:, None]

# show final tfidf feature matrix
pd.DataFrame(np.round(norm_tfidf, 2), columns=feature_names)

,pakai,honda,jazz,gk5,tahun,2014,luncur,mobil,bagus,sesuai,...,setir,trus,pelosok,undi,rentan,terjal,on,pusing,r35,mini
0,0.17,0.17,0.27,0.37,0.2,0.34,0.37,0.14,0.19,0.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.13,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
806,0.25,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.37,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
808,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
809,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
new_df = pd.read_csv('./data/test_preprocess.csv')

new_df.head()

,sentence,fuel,machine,others,part,price,service
0,Terios paling gagah . Apalagi warna merah metalic !,neutral,neutral,positive,positive,neutral,neutral
1,"gue pakai mobilio . menurut gue , bener fun to drive , enak dipakai nya .",neutral,neutral,positive,neutral,neutral,neutral
2,ya walaupun memiliki desain sporty kalau tingkat kenyamanan mobil berkurang juga berkurang kan,neutral,neutral,negative,positive,neutral,neutral
3,Xpander laku keras di pasar Indonesia .,neutral,neutral,positive,neutral,neutral,neutral
4,"Kalau mau segala enak pakai Avanza saja , mas .",neutral,neutral,positive,neutral,neutral,neutral

In [24]:
norm_corpus = normalize_corpus(list(new_df['sentence']))

new_df['clean_sentence'] = norm_corpus

new_df.head()

,sentence,fuel,machine,others,part,price,service,clean_sentence
0,Terios paling gagah . Apalagi warna merah metalic !,neutral,neutral,positive,positive,neutral,neutral,terios gagah warna merah metalic
1,"gue pakai mobilio . menurut gue , bener fun to drive , enak dipakai nya .",neutral,neutral,positive,neutral,neutral,neutral,gue pakai mobilio gue bener fun to drive pakai
2,ya walaupun memiliki desain sporty kalau tingkat kenyamanan mobil berkurang juga berkurang kan,neutral,neutral,negative,positive,neutral,neutral,milik desain sporty tingkat nyaman mobil
3,Xpander laku keras di pasar Indonesia .,neutral,neutral,positive,neutral,neutral,neutral,xpander keras pasar indonesia
4,"Kalau mau segala enak pakai Avanza saja , mas .",neutral,neutral,positive,neutral,neutral,neutral,pakai avanza mas

In [25]:
pd.DataFrame(np.round(tv.transform(new_df['clean_sentence']).toarray(), 2), columns=tv.get_feature_names_out())

,000,0001,04,08,10,100,1000,11,118,12,...,yamaha,yamahaid,yamahaindonesia,yangg,yaudah,yg,ymh,yogyakarta,zaman,zr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0